### ISSUE TITLE
Separate target packages

### ISSUE THREAD

**Issue by samdark** [yiisoft/log#12]
https://forum.yiiframework.com/t/additional-packages-for-specific-drivers-storages/125718

- [x] [log-target-db](https://github.com/yiisoft/log-target-db)
- [x] [log-target-email](https://github.com/yiisoft/log-target-email)
- [x] [log-target-file](https://github.com/yiisoft/log-target-file)
- [x] [log-target-syslog](https://github.com/yiisoft/log-target-syslog)

**Comment by machour** [comment]
All done.

Leaving this open until all impacted tests are running again.

@samdark could you enable travis for the 4 repositories and publish them to composer?
(`yiisoft/log` depends on `yiisoft/log-target-syslog` for tests)

Noticed https://travis-ci.org/yiisoft/rbac/builds/519782140 is failing because of the renaming, I'll get around it too.

**Comment by samdark** [comment]
Done with enabling travis and registering packages.
